#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged: Execute prettier and eslint on staged TypeScript files before commit
# Check package.json
yarn prettier:check && yarn lint && git add
